---
- name: Install Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name:
      - chocolatey
      - chocolatey-core.extension
    state: present
- name: Install Chocolatey Tools
  chocolatey.chocolatey.win_chocolatey:
    name:
      - pebear
      - x64dbg.portable
      - ghidra
      - cutter
      - PeStudio
      - fakenet
      - microsoft-windows-terminal
      - sysinternals
    state: present
- name: Add Choco to path
  ansible.windows.win_path:
    elements:
      - C:\ProgramData\chocolatey\bin
    state: present