---
- name: Configure Malware Analysis Machines
  hosts: [malwarelab-victim, malwarelab-analysis]
  vars_prompt:
    - name: elk_ip
      prompt: "Enter ELK Server IP"
      private: false
    - name: fleet_server_token
      prompt: "Enter Fleet Server Token"
      private: false
    - name: agent_version
      prompt: "Elastic Agent Version"
      private: false
  roles:
    - role: seclab-kali
      when: ansible_facts["distribution"] == "Kali"
    - role: malwarelab-analysis-linux
      become: true
      when: ansible_facts["distribution"] == "Kali"
    - role: malwarelab-analysis-win
      when: ansible_facts["os_family"] == "Windows"
    - role: elastic-agent
      when: ansible_facts["os_family"] == "Windows"
    - role: sysmon
      when: ansible_facts["os_family"] == "Windows"
