---
- name: Configure Malware Analysis SIEM
  hosts: malwarelab-elk
  vars:
    elk_ip: 10.1.99.106
  roles:
    - role: elk-stack
      when: ansible_facts["distribution"] == "Ubuntu"
      become: yes